version: '3.8'
services:
  adventure_works_db:
    image: postgres:15
    container_name: adventure_works
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Adventureworks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./install.sql:/install.sql
      - ./data:/data

volumes:
  postgres_data: